package granitX1.client;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Protobuf.proto

public final class Protobuf {
  private Protobuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface AttributeOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional uint32 num = 1;
    /**
     * <code>optional uint32 num = 1;</code>
     */
    boolean hasNum();
    /**
     * <code>optional uint32 num = 1;</code>
     */
    int getNum();

    // required uint32 type = 2;
    /**
     * <code>required uint32 type = 2;</code>
     */
    boolean hasType();
    /**
     * <code>required uint32 type = 2;</code>
     */
    int getType();

    // required bytes Value = 3;
    /**
     * <code>required bytes Value = 3;</code>
     */
    boolean hasValue();
    /**
     * <code>required bytes Value = 3;</code>
     */
    com.google.protobuf.ByteString getValue();
  }
  /**
   * Protobuf type {@code Attribute}
   */
  public static final class Attribute extends
      com.google.protobuf.GeneratedMessage
      implements AttributeOrBuilder {
    // Use Attribute.newBuilder() to construct.
    private Attribute(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Attribute(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Attribute defaultInstance;
    public static Attribute getDefaultInstance() {
      return defaultInstance;
    }

    public Attribute getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Attribute(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              num_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              type_ = input.readUInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              value_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Protobuf.internal_static_Attribute_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Protobuf.internal_static_Attribute_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Protobuf.Attribute.class, Protobuf.Attribute.Builder.class);
    }

    public static com.google.protobuf.Parser<Attribute> PARSER =
        new com.google.protobuf.AbstractParser<Attribute>() {
      public Attribute parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Attribute(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Attribute> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional uint32 num = 1;
    public static final int NUM_FIELD_NUMBER = 1;
    private int num_;
    /**
     * <code>optional uint32 num = 1;</code>
     */
    public boolean hasNum() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint32 num = 1;</code>
     */
    public int getNum() {
      return num_;
    }

    // required uint32 type = 2;
    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <code>required uint32 type = 2;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint32 type = 2;</code>
     */
    public int getType() {
      return type_;
    }

    // required bytes Value = 3;
    public static final int VALUE_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString value_;
    /**
     * <code>required bytes Value = 3;</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required bytes Value = 3;</code>
     */
    public com.google.protobuf.ByteString getValue() {
      return value_;
    }

    private void initFields() {
      num_ = 0;
      type_ = 0;
      value_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, num_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, type_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, value_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, num_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, type_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, value_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Protobuf.Attribute parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Protobuf.Attribute parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Protobuf.Attribute parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Protobuf.Attribute parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Protobuf.Attribute parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Protobuf.Attribute parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Protobuf.Attribute parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Protobuf.Attribute parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Protobuf.Attribute parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Protobuf.Attribute parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Protobuf.Attribute prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Attribute}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Protobuf.AttributeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Protobuf.internal_static_Attribute_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Protobuf.internal_static_Attribute_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Protobuf.Attribute.class, Protobuf.Attribute.Builder.class);
      }

      // Construct using Protobuf.Attribute.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        num_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Protobuf.internal_static_Attribute_descriptor;
      }

      public Protobuf.Attribute getDefaultInstanceForType() {
        return Protobuf.Attribute.getDefaultInstance();
      }

      public Protobuf.Attribute build() {
        Protobuf.Attribute result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Protobuf.Attribute buildPartial() {
        Protobuf.Attribute result = new Protobuf.Attribute(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.num_ = num_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Protobuf.Attribute) {
          return mergeFrom((Protobuf.Attribute)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Protobuf.Attribute other) {
        if (other == Protobuf.Attribute.getDefaultInstance()) return this;
        if (other.hasNum()) {
          setNum(other.getNum());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (!hasValue()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Protobuf.Attribute parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Protobuf.Attribute) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional uint32 num = 1;
      private int num_ ;
      /**
       * <code>optional uint32 num = 1;</code>
       */
      public boolean hasNum() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint32 num = 1;</code>
       */
      public int getNum() {
        return num_;
      }
      /**
       * <code>optional uint32 num = 1;</code>
       */
      public Builder setNum(int value) {
        bitField0_ |= 0x00000001;
        num_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 num = 1;</code>
       */
      public Builder clearNum() {
        bitField0_ = (bitField0_ & ~0x00000001);
        num_ = 0;
        onChanged();
        return this;
      }

      // required uint32 type = 2;
      private int type_ ;
      /**
       * <code>required uint32 type = 2;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint32 type = 2;</code>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>required uint32 type = 2;</code>
       */
      public Builder setType(int value) {
        bitField0_ |= 0x00000002;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 type = 2;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = 0;
        onChanged();
        return this;
      }

      // required bytes Value = 3;
      private com.google.protobuf.ByteString value_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes Value = 3;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bytes Value = 3;</code>
       */
      public com.google.protobuf.ByteString getValue() {
        return value_;
      }
      /**
       * <code>required bytes Value = 3;</code>
       */
      public Builder setValue(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes Value = 3;</code>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000004);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Attribute)
    }

    static {
      defaultInstance = new Attribute(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Attribute)
  }

  public interface EntityOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional uint32 num = 1;
    /**
     * <code>optional uint32 num = 1;</code>
     */
    boolean hasNum();
    /**
     * <code>optional uint32 num = 1;</code>
     */
    int getNum();

    // required uint32 type = 2;
    /**
     * <code>required uint32 type = 2;</code>
     */
    boolean hasType();
    /**
     * <code>required uint32 type = 2;</code>
     */
    int getType();

    // repeated .Attribute attributes = 3;
    /**
     * <code>repeated .Attribute attributes = 3;</code>
     */
    java.util.List<Protobuf.Attribute> 
        getAttributesList();
    /**
     * <code>repeated .Attribute attributes = 3;</code>
     */
    Protobuf.Attribute getAttributes(int index);
    /**
     * <code>repeated .Attribute attributes = 3;</code>
     */
    int getAttributesCount();
    /**
     * <code>repeated .Attribute attributes = 3;</code>
     */
    java.util.List<? extends Protobuf.AttributeOrBuilder> 
        getAttributesOrBuilderList();
    /**
     * <code>repeated .Attribute attributes = 3;</code>
     */
    Protobuf.AttributeOrBuilder getAttributesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Entity}
   */
  public static final class Entity extends
      com.google.protobuf.GeneratedMessage
      implements EntityOrBuilder {
    // Use Entity.newBuilder() to construct.
    private Entity(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Entity(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Entity defaultInstance;
    public static Entity getDefaultInstance() {
      return defaultInstance;
    }

    public Entity getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Entity(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              num_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              type_ = input.readUInt32();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                attributes_ = new java.util.ArrayList<Protobuf.Attribute>();
                mutable_bitField0_ |= 0x00000004;
              }
              attributes_.add(input.readMessage(Protobuf.Attribute.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          attributes_ = java.util.Collections.unmodifiableList(attributes_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Protobuf.internal_static_Entity_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Protobuf.internal_static_Entity_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Protobuf.Entity.class, Protobuf.Entity.Builder.class);
    }

    public static com.google.protobuf.Parser<Entity> PARSER =
        new com.google.protobuf.AbstractParser<Entity>() {
      public Entity parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Entity(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Entity> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional uint32 num = 1;
    public static final int NUM_FIELD_NUMBER = 1;
    private int num_;
    /**
     * <code>optional uint32 num = 1;</code>
     */
    public boolean hasNum() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint32 num = 1;</code>
     */
    public int getNum() {
      return num_;
    }

    // required uint32 type = 2;
    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <code>required uint32 type = 2;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint32 type = 2;</code>
     */
    public int getType() {
      return type_;
    }

    // repeated .Attribute attributes = 3;
    public static final int ATTRIBUTES_FIELD_NUMBER = 3;
    private java.util.List<Protobuf.Attribute> attributes_;
    /**
     * <code>repeated .Attribute attributes = 3;</code>
     */
    public java.util.List<Protobuf.Attribute> getAttributesList() {
      return attributes_;
    }
    /**
     * <code>repeated .Attribute attributes = 3;</code>
     */
    public java.util.List<? extends Protobuf.AttributeOrBuilder> 
        getAttributesOrBuilderList() {
      return attributes_;
    }
    /**
     * <code>repeated .Attribute attributes = 3;</code>
     */
    public int getAttributesCount() {
      return attributes_.size();
    }
    /**
     * <code>repeated .Attribute attributes = 3;</code>
     */
    public Protobuf.Attribute getAttributes(int index) {
      return attributes_.get(index);
    }
    /**
     * <code>repeated .Attribute attributes = 3;</code>
     */
    public Protobuf.AttributeOrBuilder getAttributesOrBuilder(
        int index) {
      return attributes_.get(index);
    }

    private void initFields() {
      num_ = 0;
      type_ = 0;
      attributes_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getAttributesCount(); i++) {
        if (!getAttributes(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, num_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, type_);
      }
      for (int i = 0; i < attributes_.size(); i++) {
        output.writeMessage(3, attributes_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, num_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, type_);
      }
      for (int i = 0; i < attributes_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, attributes_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Protobuf.Entity parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Protobuf.Entity parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Protobuf.Entity parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Protobuf.Entity parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Protobuf.Entity parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Protobuf.Entity parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Protobuf.Entity parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Protobuf.Entity parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Protobuf.Entity parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Protobuf.Entity parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Protobuf.Entity prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Entity}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Protobuf.EntityOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Protobuf.internal_static_Entity_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Protobuf.internal_static_Entity_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Protobuf.Entity.class, Protobuf.Entity.Builder.class);
      }

      // Construct using Protobuf.Entity.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAttributesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        num_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (attributesBuilder_ == null) {
          attributes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          attributesBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Protobuf.internal_static_Entity_descriptor;
      }

      public Protobuf.Entity getDefaultInstanceForType() {
        return Protobuf.Entity.getDefaultInstance();
      }

      public Protobuf.Entity build() {
        Protobuf.Entity result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Protobuf.Entity buildPartial() {
        Protobuf.Entity result = new Protobuf.Entity(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.num_ = num_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.type_ = type_;
        if (attributesBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            attributes_ = java.util.Collections.unmodifiableList(attributes_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.attributes_ = attributes_;
        } else {
          result.attributes_ = attributesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Protobuf.Entity) {
          return mergeFrom((Protobuf.Entity)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Protobuf.Entity other) {
        if (other == Protobuf.Entity.getDefaultInstance()) return this;
        if (other.hasNum()) {
          setNum(other.getNum());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (attributesBuilder_ == null) {
          if (!other.attributes_.isEmpty()) {
            if (attributes_.isEmpty()) {
              attributes_ = other.attributes_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureAttributesIsMutable();
              attributes_.addAll(other.attributes_);
            }
            onChanged();
          }
        } else {
          if (!other.attributes_.isEmpty()) {
            if (attributesBuilder_.isEmpty()) {
              attributesBuilder_.dispose();
              attributesBuilder_ = null;
              attributes_ = other.attributes_;
              bitField0_ = (bitField0_ & ~0x00000004);
              attributesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getAttributesFieldBuilder() : null;
            } else {
              attributesBuilder_.addAllMessages(other.attributes_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        for (int i = 0; i < getAttributesCount(); i++) {
          if (!getAttributes(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Protobuf.Entity parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Protobuf.Entity) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional uint32 num = 1;
      private int num_ ;
      /**
       * <code>optional uint32 num = 1;</code>
       */
      public boolean hasNum() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint32 num = 1;</code>
       */
      public int getNum() {
        return num_;
      }
      /**
       * <code>optional uint32 num = 1;</code>
       */
      public Builder setNum(int value) {
        bitField0_ |= 0x00000001;
        num_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 num = 1;</code>
       */
      public Builder clearNum() {
        bitField0_ = (bitField0_ & ~0x00000001);
        num_ = 0;
        onChanged();
        return this;
      }

      // required uint32 type = 2;
      private int type_ ;
      /**
       * <code>required uint32 type = 2;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint32 type = 2;</code>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>required uint32 type = 2;</code>
       */
      public Builder setType(int value) {
        bitField0_ |= 0x00000002;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 type = 2;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = 0;
        onChanged();
        return this;
      }

      // repeated .Attribute attributes = 3;
      private java.util.List<Protobuf.Attribute> attributes_ =
        java.util.Collections.emptyList();
      private void ensureAttributesIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          attributes_ = new java.util.ArrayList<Protobuf.Attribute>(attributes_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          Protobuf.Attribute, Protobuf.Attribute.Builder, Protobuf.AttributeOrBuilder> attributesBuilder_;

      /**
       * <code>repeated .Attribute attributes = 3;</code>
       */
      public java.util.List<Protobuf.Attribute> getAttributesList() {
        if (attributesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(attributes_);
        } else {
          return attributesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Attribute attributes = 3;</code>
       */
      public int getAttributesCount() {
        if (attributesBuilder_ == null) {
          return attributes_.size();
        } else {
          return attributesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Attribute attributes = 3;</code>
       */
      public Protobuf.Attribute getAttributes(int index) {
        if (attributesBuilder_ == null) {
          return attributes_.get(index);
        } else {
          return attributesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Attribute attributes = 3;</code>
       */
      public Builder setAttributes(
          int index, Protobuf.Attribute value) {
        if (attributesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttributesIsMutable();
          attributes_.set(index, value);
          onChanged();
        } else {
          attributesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Attribute attributes = 3;</code>
       */
      public Builder setAttributes(
          int index, Protobuf.Attribute.Builder builderForValue) {
        if (attributesBuilder_ == null) {
          ensureAttributesIsMutable();
          attributes_.set(index, builderForValue.build());
          onChanged();
        } else {
          attributesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Attribute attributes = 3;</code>
       */
      public Builder addAttributes(Protobuf.Attribute value) {
        if (attributesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttributesIsMutable();
          attributes_.add(value);
          onChanged();
        } else {
          attributesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Attribute attributes = 3;</code>
       */
      public Builder addAttributes(
          int index, Protobuf.Attribute value) {
        if (attributesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttributesIsMutable();
          attributes_.add(index, value);
          onChanged();
        } else {
          attributesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Attribute attributes = 3;</code>
       */
      public Builder addAttributes(
          Protobuf.Attribute.Builder builderForValue) {
        if (attributesBuilder_ == null) {
          ensureAttributesIsMutable();
          attributes_.add(builderForValue.build());
          onChanged();
        } else {
          attributesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Attribute attributes = 3;</code>
       */
      public Builder addAttributes(
          int index, Protobuf.Attribute.Builder builderForValue) {
        if (attributesBuilder_ == null) {
          ensureAttributesIsMutable();
          attributes_.add(index, builderForValue.build());
          onChanged();
        } else {
          attributesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Attribute attributes = 3;</code>
       */
      public Builder addAllAttributes(
          java.lang.Iterable<? extends Protobuf.Attribute> values) {
        if (attributesBuilder_ == null) {
          ensureAttributesIsMutable();
          super.addAll(values, attributes_);
          onChanged();
        } else {
          attributesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Attribute attributes = 3;</code>
       */
      public Builder clearAttributes() {
        if (attributesBuilder_ == null) {
          attributes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          attributesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Attribute attributes = 3;</code>
       */
      public Builder removeAttributes(int index) {
        if (attributesBuilder_ == null) {
          ensureAttributesIsMutable();
          attributes_.remove(index);
          onChanged();
        } else {
          attributesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Attribute attributes = 3;</code>
       */
      public Protobuf.Attribute.Builder getAttributesBuilder(
          int index) {
        return getAttributesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Attribute attributes = 3;</code>
       */
      public Protobuf.AttributeOrBuilder getAttributesOrBuilder(
          int index) {
        if (attributesBuilder_ == null) {
          return attributes_.get(index);  } else {
          return attributesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Attribute attributes = 3;</code>
       */
      public java.util.List<? extends Protobuf.AttributeOrBuilder> 
           getAttributesOrBuilderList() {
        if (attributesBuilder_ != null) {
          return attributesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(attributes_);
        }
      }
      /**
       * <code>repeated .Attribute attributes = 3;</code>
       */
      public Protobuf.Attribute.Builder addAttributesBuilder() {
        return getAttributesFieldBuilder().addBuilder(
            Protobuf.Attribute.getDefaultInstance());
      }
      /**
       * <code>repeated .Attribute attributes = 3;</code>
       */
      public Protobuf.Attribute.Builder addAttributesBuilder(
          int index) {
        return getAttributesFieldBuilder().addBuilder(
            index, Protobuf.Attribute.getDefaultInstance());
      }
      /**
       * <code>repeated .Attribute attributes = 3;</code>
       */
      public java.util.List<Protobuf.Attribute.Builder> 
           getAttributesBuilderList() {
        return getAttributesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          Protobuf.Attribute, Protobuf.Attribute.Builder, Protobuf.AttributeOrBuilder> 
          getAttributesFieldBuilder() {
        if (attributesBuilder_ == null) {
          attributesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              Protobuf.Attribute, Protobuf.Attribute.Builder, Protobuf.AttributeOrBuilder>(
                  attributes_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          attributes_ = null;
        }
        return attributesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Entity)
    }

    static {
      defaultInstance = new Entity(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Entity)
  }

  public interface TaskOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .Task.Commands Command = 1;
    /**
     * <code>optional .Task.Commands Command = 1;</code>
     */
    boolean hasCommand();
    /**
     * <code>optional .Task.Commands Command = 1;</code>
     */
    Protobuf.Task.Commands getCommand();

    // repeated .Entity Entities = 2;
    /**
     * <code>repeated .Entity Entities = 2;</code>
     */
    java.util.List<Protobuf.Entity> 
        getEntitiesList();
    /**
     * <code>repeated .Entity Entities = 2;</code>
     */
    Protobuf.Entity getEntities(int index);
    /**
     * <code>repeated .Entity Entities = 2;</code>
     */
    int getEntitiesCount();
    /**
     * <code>repeated .Entity Entities = 2;</code>
     */
    java.util.List<? extends Protobuf.EntityOrBuilder> 
        getEntitiesOrBuilderList();
    /**
     * <code>repeated .Entity Entities = 2;</code>
     */
    Protobuf.EntityOrBuilder getEntitiesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Task}
   */
  public static final class Task extends
      com.google.protobuf.GeneratedMessage
      implements TaskOrBuilder {
    // Use Task.newBuilder() to construct.
    private Task(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Task(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Task defaultInstance;
    public static Task getDefaultInstance() {
      return defaultInstance;
    }

    public Task getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Task(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              Protobuf.Task.Commands value = Protobuf.Task.Commands.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                command_ = value;
              }
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                entities_ = new java.util.ArrayList<Protobuf.Entity>();
                mutable_bitField0_ |= 0x00000002;
              }
              entities_.add(input.readMessage(Protobuf.Entity.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          entities_ = java.util.Collections.unmodifiableList(entities_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Protobuf.internal_static_Task_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Protobuf.internal_static_Task_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Protobuf.Task.class, Protobuf.Task.Builder.class);
    }

    public static com.google.protobuf.Parser<Task> PARSER =
        new com.google.protobuf.AbstractParser<Task>() {
      public Task parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Task(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Task> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code Task.Commands}
     */
    public enum Commands
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>READ_ENTITY = 0;</code>
       */
      READ_ENTITY(0, 0),
      /**
       * <code>READ_ATTRIBUTE = 1;</code>
       */
      READ_ATTRIBUTE(1, 1),
      /**
       * <code>WRITE_ENTITY = 2;</code>
       */
      WRITE_ENTITY(2, 2),
      /**
       * <code>DELETE_ENTITY = 3;</code>
       */
      DELETE_ENTITY(3, 3),
      /**
       * <code>DELETE_ATTRIBUTE = 4;</code>
       */
      DELETE_ATTRIBUTE(4, 4),
      ;

      /**
       * <code>READ_ENTITY = 0;</code>
       */
      public static final int READ_ENTITY_VALUE = 0;
      /**
       * <code>READ_ATTRIBUTE = 1;</code>
       */
      public static final int READ_ATTRIBUTE_VALUE = 1;
      /**
       * <code>WRITE_ENTITY = 2;</code>
       */
      public static final int WRITE_ENTITY_VALUE = 2;
      /**
       * <code>DELETE_ENTITY = 3;</code>
       */
      public static final int DELETE_ENTITY_VALUE = 3;
      /**
       * <code>DELETE_ATTRIBUTE = 4;</code>
       */
      public static final int DELETE_ATTRIBUTE_VALUE = 4;


      public final int getNumber() { return value; }

      public static Commands valueOf(int value) {
        switch (value) {
          case 0: return READ_ENTITY;
          case 1: return READ_ATTRIBUTE;
          case 2: return WRITE_ENTITY;
          case 3: return DELETE_ENTITY;
          case 4: return DELETE_ATTRIBUTE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Commands>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Commands>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Commands>() {
              public Commands findValueByNumber(int number) {
                return Commands.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return Protobuf.Task.getDescriptor().getEnumTypes().get(0);
      }

      private static final Commands[] VALUES = values();

      public static Commands valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Commands(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Task.Commands)
    }

    private int bitField0_;
    // optional .Task.Commands Command = 1;
    public static final int COMMAND_FIELD_NUMBER = 1;
    private Protobuf.Task.Commands command_;
    /**
     * <code>optional .Task.Commands Command = 1;</code>
     */
    public boolean hasCommand() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .Task.Commands Command = 1;</code>
     */
    public Protobuf.Task.Commands getCommand() {
      return command_;
    }

    // repeated .Entity Entities = 2;
    public static final int ENTITIES_FIELD_NUMBER = 2;
    private java.util.List<Protobuf.Entity> entities_;
    /**
     * <code>repeated .Entity Entities = 2;</code>
     */
    public java.util.List<Protobuf.Entity> getEntitiesList() {
      return entities_;
    }
    /**
     * <code>repeated .Entity Entities = 2;</code>
     */
    public java.util.List<? extends Protobuf.EntityOrBuilder> 
        getEntitiesOrBuilderList() {
      return entities_;
    }
    /**
     * <code>repeated .Entity Entities = 2;</code>
     */
    public int getEntitiesCount() {
      return entities_.size();
    }
    /**
     * <code>repeated .Entity Entities = 2;</code>
     */
    public Protobuf.Entity getEntities(int index) {
      return entities_.get(index);
    }
    /**
     * <code>repeated .Entity Entities = 2;</code>
     */
    public Protobuf.EntityOrBuilder getEntitiesOrBuilder(
        int index) {
      return entities_.get(index);
    }

    private void initFields() {
      command_ = Protobuf.Task.Commands.READ_ENTITY;
      entities_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getEntitiesCount(); i++) {
        if (!getEntities(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, command_.getNumber());
      }
      for (int i = 0; i < entities_.size(); i++) {
        output.writeMessage(2, entities_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, command_.getNumber());
      }
      for (int i = 0; i < entities_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, entities_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Protobuf.Task parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Protobuf.Task parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Protobuf.Task parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Protobuf.Task parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Protobuf.Task parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Protobuf.Task parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Protobuf.Task parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Protobuf.Task parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Protobuf.Task parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Protobuf.Task parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Protobuf.Task prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Task}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Protobuf.TaskOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Protobuf.internal_static_Task_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Protobuf.internal_static_Task_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Protobuf.Task.class, Protobuf.Task.Builder.class);
      }

      // Construct using Protobuf.Task.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getEntitiesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        command_ = Protobuf.Task.Commands.READ_ENTITY;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (entitiesBuilder_ == null) {
          entities_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          entitiesBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Protobuf.internal_static_Task_descriptor;
      }

      public Protobuf.Task getDefaultInstanceForType() {
        return Protobuf.Task.getDefaultInstance();
      }

      public Protobuf.Task build() {
        Protobuf.Task result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Protobuf.Task buildPartial() {
        Protobuf.Task result = new Protobuf.Task(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.command_ = command_;
        if (entitiesBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            entities_ = java.util.Collections.unmodifiableList(entities_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.entities_ = entities_;
        } else {
          result.entities_ = entitiesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Protobuf.Task) {
          return mergeFrom((Protobuf.Task)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Protobuf.Task other) {
        if (other == Protobuf.Task.getDefaultInstance()) return this;
        if (other.hasCommand()) {
          setCommand(other.getCommand());
        }
        if (entitiesBuilder_ == null) {
          if (!other.entities_.isEmpty()) {
            if (entities_.isEmpty()) {
              entities_ = other.entities_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureEntitiesIsMutable();
              entities_.addAll(other.entities_);
            }
            onChanged();
          }
        } else {
          if (!other.entities_.isEmpty()) {
            if (entitiesBuilder_.isEmpty()) {
              entitiesBuilder_.dispose();
              entitiesBuilder_ = null;
              entities_ = other.entities_;
              bitField0_ = (bitField0_ & ~0x00000002);
              entitiesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getEntitiesFieldBuilder() : null;
            } else {
              entitiesBuilder_.addAllMessages(other.entities_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getEntitiesCount(); i++) {
          if (!getEntities(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Protobuf.Task parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Protobuf.Task) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .Task.Commands Command = 1;
      private Protobuf.Task.Commands command_ = Protobuf.Task.Commands.READ_ENTITY;
      /**
       * <code>optional .Task.Commands Command = 1;</code>
       */
      public boolean hasCommand() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .Task.Commands Command = 1;</code>
       */
      public Protobuf.Task.Commands getCommand() {
        return command_;
      }
      /**
       * <code>optional .Task.Commands Command = 1;</code>
       */
      public Builder setCommand(Protobuf.Task.Commands value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        command_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .Task.Commands Command = 1;</code>
       */
      public Builder clearCommand() {
        bitField0_ = (bitField0_ & ~0x00000001);
        command_ = Protobuf.Task.Commands.READ_ENTITY;
        onChanged();
        return this;
      }

      // repeated .Entity Entities = 2;
      private java.util.List<Protobuf.Entity> entities_ =
        java.util.Collections.emptyList();
      private void ensureEntitiesIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          entities_ = new java.util.ArrayList<Protobuf.Entity>(entities_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          Protobuf.Entity, Protobuf.Entity.Builder, Protobuf.EntityOrBuilder> entitiesBuilder_;

      /**
       * <code>repeated .Entity Entities = 2;</code>
       */
      public java.util.List<Protobuf.Entity> getEntitiesList() {
        if (entitiesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(entities_);
        } else {
          return entitiesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Entity Entities = 2;</code>
       */
      public int getEntitiesCount() {
        if (entitiesBuilder_ == null) {
          return entities_.size();
        } else {
          return entitiesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Entity Entities = 2;</code>
       */
      public Protobuf.Entity getEntities(int index) {
        if (entitiesBuilder_ == null) {
          return entities_.get(index);
        } else {
          return entitiesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Entity Entities = 2;</code>
       */
      public Builder setEntities(
          int index, Protobuf.Entity value) {
        if (entitiesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEntitiesIsMutable();
          entities_.set(index, value);
          onChanged();
        } else {
          entitiesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Entity Entities = 2;</code>
       */
      public Builder setEntities(
          int index, Protobuf.Entity.Builder builderForValue) {
        if (entitiesBuilder_ == null) {
          ensureEntitiesIsMutable();
          entities_.set(index, builderForValue.build());
          onChanged();
        } else {
          entitiesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Entity Entities = 2;</code>
       */
      public Builder addEntities(Protobuf.Entity value) {
        if (entitiesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEntitiesIsMutable();
          entities_.add(value);
          onChanged();
        } else {
          entitiesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Entity Entities = 2;</code>
       */
      public Builder addEntities(
          int index, Protobuf.Entity value) {
        if (entitiesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEntitiesIsMutable();
          entities_.add(index, value);
          onChanged();
        } else {
          entitiesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Entity Entities = 2;</code>
       */
      public Builder addEntities(
          Protobuf.Entity.Builder builderForValue) {
        if (entitiesBuilder_ == null) {
          ensureEntitiesIsMutable();
          entities_.add(builderForValue.build());
          onChanged();
        } else {
          entitiesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Entity Entities = 2;</code>
       */
      public Builder addEntities(
          int index, Protobuf.Entity.Builder builderForValue) {
        if (entitiesBuilder_ == null) {
          ensureEntitiesIsMutable();
          entities_.add(index, builderForValue.build());
          onChanged();
        } else {
          entitiesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Entity Entities = 2;</code>
       */
      public Builder addAllEntities(
          java.lang.Iterable<? extends Protobuf.Entity> values) {
        if (entitiesBuilder_ == null) {
          ensureEntitiesIsMutable();
          super.addAll(values, entities_);
          onChanged();
        } else {
          entitiesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Entity Entities = 2;</code>
       */
      public Builder clearEntities() {
        if (entitiesBuilder_ == null) {
          entities_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          entitiesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Entity Entities = 2;</code>
       */
      public Builder removeEntities(int index) {
        if (entitiesBuilder_ == null) {
          ensureEntitiesIsMutable();
          entities_.remove(index);
          onChanged();
        } else {
          entitiesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Entity Entities = 2;</code>
       */
      public Protobuf.Entity.Builder getEntitiesBuilder(
          int index) {
        return getEntitiesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Entity Entities = 2;</code>
       */
      public Protobuf.EntityOrBuilder getEntitiesOrBuilder(
          int index) {
        if (entitiesBuilder_ == null) {
          return entities_.get(index);  } else {
          return entitiesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Entity Entities = 2;</code>
       */
      public java.util.List<? extends Protobuf.EntityOrBuilder> 
           getEntitiesOrBuilderList() {
        if (entitiesBuilder_ != null) {
          return entitiesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(entities_);
        }
      }
      /**
       * <code>repeated .Entity Entities = 2;</code>
       */
      public Protobuf.Entity.Builder addEntitiesBuilder() {
        return getEntitiesFieldBuilder().addBuilder(
            Protobuf.Entity.getDefaultInstance());
      }
      /**
       * <code>repeated .Entity Entities = 2;</code>
       */
      public Protobuf.Entity.Builder addEntitiesBuilder(
          int index) {
        return getEntitiesFieldBuilder().addBuilder(
            index, Protobuf.Entity.getDefaultInstance());
      }
      /**
       * <code>repeated .Entity Entities = 2;</code>
       */
      public java.util.List<Protobuf.Entity.Builder> 
           getEntitiesBuilderList() {
        return getEntitiesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          Protobuf.Entity, Protobuf.Entity.Builder, Protobuf.EntityOrBuilder> 
          getEntitiesFieldBuilder() {
        if (entitiesBuilder_ == null) {
          entitiesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              Protobuf.Entity, Protobuf.Entity.Builder, Protobuf.EntityOrBuilder>(
                  entities_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          entities_ = null;
        }
        return entitiesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Task)
    }

    static {
      defaultInstance = new Task(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Task)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Attribute_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Attribute_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Entity_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Entity_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Task_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Task_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Protobuf.proto\"5\n\tAttribute\022\013\n\003num\030\001 \001" +
      "(\r\022\014\n\004type\030\002 \002(\r\022\r\n\005Value\030\003 \002(\014\"C\n\006Entit" +
      "y\022\013\n\003num\030\001 \001(\r\022\014\n\004type\030\002 \002(\r\022\036\n\nattribut" +
      "es\030\003 \003(\0132\n.Attribute\"\256\001\n\004Task\022\037\n\007Command" +
      "\030\001 \001(\0162\016.Task.Commands\022\031\n\010Entities\030\002 \003(\013" +
      "2\007.Entity\"j\n\010Commands\022\017\n\013READ_ENTITY\020\000\022\022" +
      "\n\016READ_ATTRIBUTE\020\001\022\020\n\014WRITE_ENTITY\020\002\022\021\n\r" +
      "DELETE_ENTITY\020\003\022\024\n\020DELETE_ATTRIBUTE\020\004"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Attribute_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Attribute_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Attribute_descriptor,
              new java.lang.String[] { "Num", "Type", "Value", });
          internal_static_Entity_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Entity_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Entity_descriptor,
              new java.lang.String[] { "Num", "Type", "Attributes", });
          internal_static_Task_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_Task_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Task_descriptor,
              new java.lang.String[] { "Command", "Entities", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
